//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateTimeConsoleClient.DateNamer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DateNamer.INameOfDate")]
    public interface INameOfDate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INameOfDate/GetNameOfDate", ReplyAction="http://tempuri.org/INameOfDate/GetNameOfDateResponse")]
        string GetNameOfDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INameOfDate/GetNameOfDate", ReplyAction="http://tempuri.org/INameOfDate/GetNameOfDateResponse")]
        System.Threading.Tasks.Task<string> GetNameOfDateAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INameOfDateChannel : DateTimeConsoleClient.DateNamer.INameOfDate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NameOfDateClient : System.ServiceModel.ClientBase<DateTimeConsoleClient.DateNamer.INameOfDate>, DateTimeConsoleClient.DateNamer.INameOfDate {
        
        public NameOfDateClient() {
        }
        
        public NameOfDateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NameOfDateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NameOfDateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NameOfDateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetNameOfDate(System.DateTime date) {
            return base.Channel.GetNameOfDate(date);
        }
        
        public System.Threading.Tasks.Task<string> GetNameOfDateAsync(System.DateTime date) {
            return base.Channel.GetNameOfDateAsync(date);
        }
    }
}
