//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Continents
    {
        public Continents()
        {
            this.Country = new HashSet<Country>();
        }
    
        public int ContinentId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Country> Country { get; set; }
    }
}
